# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\vscode\py\test\changebag\mainwindow\mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(596, 396)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("e:\\vscode\\py\\test\\changebag\\mainwindow\\../icons/icon_soft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.label_image_src = QtWidgets.QLabel(Form)
        self.label_image_src.setGeometry(QtCore.QRect(160, 70, 131, 161))
        self.label_image_src.setStyleSheet("")
        self.label_image_src.setText("")
        self.label_image_src.setTextFormat(QtCore.Qt.PlainText)
        self.label_image_src.setObjectName("label_image_src")
        self.label_image_tar = QtWidgets.QLabel(Form)
        self.label_image_tar.setGeometry(QtCore.QRect(410, 70, 221, 161))
        self.label_image_tar.setStyleSheet("")
        self.label_image_tar.setText("")
        self.label_image_tar.setObjectName("label_image_tar")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 30, 321, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_src = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_src.setFont(font)
        self.label_src.setObjectName("label_src")
        self.horizontalLayout_2.addWidget(self.label_src)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_tar = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_tar.setFont(font)
        self.label_tar.setObjectName("label_tar")
        self.horizontalLayout_2.addWidget(self.label_tar)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 101, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_open = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setStyleSheet("QPushButton::pressed{\n"
"background-color: rgba(164, 173, 179, 0.8);\n"
"border:0;\n"
"color:black;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("e:\\vscode\\py\\test\\changebag\\mainwindow\\../icons/icon_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_open.setIcon(icon1)
        self.pushButton_open.setObjectName("pushButton_open")
        self.verticalLayout.addWidget(self.pushButton_open)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_start = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton::pressed{\n"
"background-color: rgba(164, 173, 179, 0.8);\n"
"border:0;\n"
"color:black;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("e:\\vscode\\py\\test\\changebag\\mainwindow\\../icons/icon_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start.setIcon(icon2)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton::pressed{\n"
"background-color: rgba(164, 173, 179, 0.8);\n"
"border:0;\n"
"color:black;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("e:\\vscode\\py\\test\\changebag\\mainwindow\\../icons/icon_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon3)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout.addWidget(self.pushButton_save)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 300, 481, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget2)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_bag = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_bag.setFont(font)
        self.label_bag.setObjectName("label_bag")
        self.horizontalLayout.addWidget(self.label_bag)
        self.radioButton_white = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_white.setFont(font)
        self.radioButton_white.setObjectName("radioButton_white")
        self.horizontalLayout.addWidget(self.radioButton_white)
        self.radioButton_red = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_red.setFont(font)
        self.radioButton_red.setObjectName("radioButton_red")
        self.horizontalLayout.addWidget(self.radioButton_red)
        self.radioButton_blue = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_blue.setFont(font)
        self.radioButton_blue.setObjectName("radioButton_blue")
        self.horizontalLayout.addWidget(self.radioButton_blue)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(290, 261, 151, 20))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"text-align: center;\n"
"background-color: #e2e3e4;\n"
"border: 1px solid #999999;\n"
"border-radius: 5px;}\n"
"QProgressBar::chunk{background-color: #995fff;\n"
"border-radius: 5px;}")
        self.progressBar.setProperty("value", 1)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "证件照背景换色"))
        self.label_src.setText(_translate("Form", "原始图片"))
        self.label_tar.setText(_translate("Form", "转换结果"))
        self.pushButton_open.setText(_translate("Form", "打开文件"))
        self.pushButton_start.setText(_translate("Form", "开始替换"))
        self.pushButton_save.setText(_translate("Form", "保存图片"))
        self.label_bag.setText(_translate("Form", "背景选择"))
        self.radioButton_white.setText(_translate("Form", "白色"))
        self.radioButton_red.setText(_translate("Form", "红色"))
        self.radioButton_blue.setText(_translate("Form", "蓝色"))
        self.progressBar.setFormat(_translate("Form", "正在替换%p%"))
